fix: add retry for downloading

diff --git a/src/libexec/rsdk/rsdk-infra-pkg-download b/src/libexec/rsdk/rsdk-infra-pkg-download
--- a/src/libexec/rsdk/rsdk-infra-pkg-download
+++ b/src/libexec/rsdk/rsdk-infra-pkg-download
@@ -43,7 +43,14 @@ download_pkgs() {
 			mkdir -p "$RSDK_TEMP/$pkg"
 
 			if [[ $RSDK_OPTION_DRY_RUN == "false" ]]; then
-				gh release download "$tag" --repo "$org/$pkg" --dir "$RSDK_TEMP/$pkg"
+				retry=3
+				while ! gh release download "$tag" --repo "$org/$pkg" --dir "$RSDK_TEMP/$pkg"; do
+					if ((retry-- <= 0)); then
+						echo "Failed to download '$org/$pkg@$tag', aborting."
+						return 2
+					fi
+					sleep 5
+				done
 				if [[ ! -f "$RSDK_TEMP/$pkg/pkg.conf" ]]; then
 					if [[ $RSDK_OPTION_DEFAULT_DISTRO == "true" ]]; then
 						cp "$RSDK_TEMP/$pkg"/*.deb "$OUTPUT/${DISTROS[0]}"
