fix: do not exit if workflow failed to run in one repo

diff --git a/.github/actions/infra-repo-update/action.yaml b/.github/actions/infra-repo-update/action.yaml
--- a/.github/actions/infra-repo-update/action.yaml
+++ b/.github/actions/infra-repo-update/action.yaml
@@ -48,7 +48,9 @@ runs:
         for distro in "${supported_distros[@]}"
         do
           if gh repo view "$repo_org/$distro$repo_suffix" &>/dev/null; then
-            gh workflow run .github/workflows/update.yaml --repo "$repo_org/$distro$repo_suffix"
+            if ! gh workflow run .github/workflows/update.yaml --repo "$repo_org/$distro$repo_suffix"; then
+              echo "Failed to dispatch workflow for $repo_org/$distro$repo_suffix"
+            fi
           else
             echo "$repo_org/$distro$repo_suffix does not exist. Skip."
           fi
